const fs = require('fs');
const path = require('path');
const { generateSeoMetaTags } = require('./seo_generator');

// Load master catalog data
const appData = JSON.parse(fs.readFileSync('app.json', 'utf8'));
const productCatalog = appData.product_catalog;

const files = fs.readdirSync(__dirname).filter(f => f.endsWith('.html') && f !== 'challenge-blog.html' && f !== 'product-template.html');

files.forEach(file => {
    let content = fs.readFileSync(file, 'utf8');
    const productId = file.replace('.html', '');

    // 1. Extract data from HTML or app.json
    let productInCatalog = productCatalog.find(p => p.id === productId);
    
    let titleMatch = content.match(/<title>(.*?)<\/title>/);
    let titleStr = titleMatch ? titleMatch[1] : (productInCatalog ? productInCatalog.name + ' | Aura cares' : 'Aura cares Global Healthcare');
    let shortName = titleStr.split('|')[0].trim();

    let descMatch = content.match(/<meta name="description" content="(.*?)">/);
    let descStr = descMatch ? descMatch[1] : (productInCatalog ? productInCatalog.use : 'Premium Aura cares Healthcare Protocol formulated by global standards.');

    let imageUrl = 'https://auracares.vercel.app/' + encodeURIComponent(shortName) + '.png';
    if(file === 'index.html') imageUrl = 'https://auracares.vercel.app/Reishi.png';
    
    let pageUrl = 'https://auracares.vercel.app/' + file;
    if(file === 'index.html') pageUrl = 'https://auracares.vercel.app/';

    // Get keywords from app.json if available, else use generic
    let keywords = productInCatalog && productInCatalog.keywords ? productInCatalog.keywords : [shortName, 'Aura cares', 'Natural Supplement', 'Wellness'];
    
    // 2. Extract existing vital links and scripts (CSS, JS, manifest)
    let assets = [];
    const assetRegex = /<(link|script|style)(?! type="application\/ld\+json")[^>]*?>([\s\S]*?<\/\1>)?/g;
    let match;
    while ((match = assetRegex.exec(content)) !== null) {
        // Only keep assets that are in the head
        if (content.indexOf(match[0]) < content.indexOf('</head>')) {
            const assetTag = match[0];
            // EXCLUDE canonical links and favicons as they are generated by the utility
            if (assetTag.includes('rel="canonical"') || assetTag.includes('rel="icon"') || assetTag.includes('rel="shortcut icon"')) {
                continue;
            }
            assets.push(assetTag);
        }
    }

    // 3. Prepare pageData
    const pageData = {
        title: titleStr,
        description: descStr,
        keywords: keywords,
        dataKeywords: keywords.slice(0, 5), // Use first 5 as high-priority data keywords
        canonicalUrl: pageUrl,
        ogImage: imageUrl,
        price: productInCatalog ? productInCatalog.price : 20000,
        category: 'Healthcare',
        keyFacts: [
            shortName + ' is part of the Aura cares global wellness ecosystem.',
            productInCatalog ? productInCatalog.use : 'Standardized herbal formulation for maximum potency.'
        ]
    };

    // 4. Generate meta tags using utility
    const meta = generateSeoMetaTags(pageData);
    
    let metaHtml = `    <!-- ======= ADVANCED SEO, AEO & DEO (GENERATED BY UTILITY) ======= -->\n`;
    metaHtml += `    ${meta.charset}\n`;
    metaHtml += `    ${meta.viewport}\n`;
    metaHtml += `    ${meta.language}\n`;
    metaHtml += `    ${meta.title}\n`;
    metaHtml += `    ${meta.description}\n`;
    metaHtml += `    ${meta.keywords}\n`;
    metaHtml += `    ${meta.canonical}\n`;
    metaHtml += `    ${meta.robots}\n`;
    metaHtml += `    \n    <!-- Open Graph -->\n`;
    metaHtml += `    ${meta.ogSiteName}\n`;
    metaHtml += `    ${meta.ogTitle}\n`;
    metaHtml += `    ${meta.ogDescription}\n`;
    metaHtml += `    ${meta.ogImage}\n`;
    metaHtml += `    ${meta.ogImageSecure}\n`;
    metaHtml += `    ${meta.ogImageWidth}\n`;
    metaHtml += `    ${meta.ogImageHeight}\n`;
    metaHtml += `    ${meta.ogImageAlt}\n`;
    metaHtml += `    ${meta.ogUrl}\n`;
    metaHtml += `    ${meta.ogType}\n`;
    metaHtml += `    \n    <!-- Twitter Card -->\n`;
    metaHtml += `    ${meta.twitterCard}\n`;
    metaHtml += `    ${meta.twitterTitle}\n`;
    metaHtml += `    ${meta.twitterDescription}\n`;
    metaHtml += `    ${meta.twitterImage}\n`;
    metaHtml += `    \n    <!-- AI Engine Optimization -->\n`;
    metaHtml += `    ${meta.aiSnippet}\n`;
    metaHtml += `    ${meta.knowledge}\n`;
    metaHtml += `    ${meta.llmOptimization}\n`;
    metaHtml += `    \n    <!-- Data Engine Optimization -->\n`;
    metaHtml += `    ${meta.dataSchema}\n`;
    metaHtml += `    ${meta.dataKeywords}\n`;
    metaHtml += `    ${meta.apiEndpoint}\n`;
    metaHtml += `    \n    <!-- Structured Data -->\n`;
    metaHtml += `    ${meta.schemaProduct}\n`;
    metaHtml += `    ${meta.schemaBreadcrumb}\n`;
    metaHtml += `    ${meta.schemaOrganization}\n`;
    metaHtml += `    \n    <!-- Meta Extras -->\n`;
    metaHtml += `    ${meta.author}\n`;
    metaHtml += `    ${meta.publisher}\n`;
    metaHtml += `    ${meta.revisitAfter}\n`;
    metaHtml += `    ${meta.expires}\n`;

    // 5. Rebuild the Entire Head
    let newHead = `<head>\n${metaHtml}\n    \n    <!-- Assets -->\n    ` + assets.join('\n    ') + `\n</head>`;
    
    content = content.replace(/<head>[\s\S]*?<\/head>/, newHead);

    fs.writeFileSync(file, content);
});

console.log("All pages fully refactored with product-specific keywords from app.json.");

